%% Pdistribution_averaged.m
% Compute and plot the averaged orientation distribution P(theta)
% from director field data generated by the defect analysis pipeline.
%
% Expected input directory structure (relative to repo root):
%   Data/<run_name>/
%       director_data_*.mat
%
% Outputs:
%   Results/Ptheta_averaged_<run_name>.pdf (or .tif)
%
% This script is intended to reproduce orientation-distribution figures
% used in the main text and Supporting Information.
%
% Copyright (c) 2025 Zhaofei Zheng
% Released under the MIT License. See LICENSE in the repository root.

clear
clc

% -------------------- Repo-safe paths (do not use pwd) --------------------
repoRoot = fileparts(fileparts(mfilename("fullpath"))); % scripts/ → repo root

% --------- User-adjustable dataset name (relative to Data/) --------------
runName = 'Pdistribution';

% Input directory containing director_data_*.mat
dataDir = fullfile(repoRoot, 'data/sample', runName);

% Output directory for final figures
resultDir = fullfile(repoRoot, 'Results');
if ~exist(resultDir, 'dir')
    mkdir(resultDir);
end

% List of file pairs to average
directorList = {
    {'director_data_10_01.mat', 'director_data_10_02.mat'}, ...
    {'director_data_30_01.mat', 'director_data_30_02.mat'}, ...
    {'director_data_50_01.mat', 'director_data_50_02.mat'}, ...
    {'director_data_70_01.mat', 'director_data_70_02.mat'}
};

legendNames = {'10%MF', '30%MF', '50%MF', '70%MF'};
markerList = {'o', 's', '^', 'd'};

% Histogram bin setup
numBins     = 50;
edges       = linspace(-pi, pi, numBins + 1);
binCenters  = edges(1:end-1) + diff(edges)/2;
binWidth    = edges(2) - edges(1);

% === Use zfcolors ===
addpath('/Users/zhaofei/Documents/MATLAB');
cols = zfcolors();   
colorOrder = cols(1:numel(directorList), :);

% Create figure
fig = figure('Color','w');
ax  = axes('Parent',fig); hold(ax,'on'); box(ax,'on'); grid(ax,'off');

hPlot = gobjects(1, numel(directorList)); % store handles

for k = 1:numel(directorList)
    pdfSum = zeros(1, numBins);  
    
    for j = 1:2
        filePath = fullfile(dataDir, directorList{k}{j});
        data = load(filePath);
        cosTheta = data.directors(:,:,1);
        sinTheta = data.directors(:,:,2);
        theta = atan2(sinTheta, cosTheta);
        thetaVec = theta(:);

        % Mean subtraction
        meanTheta = atan2(mean(sin(thetaVec)), mean(cos(thetaVec)));
        deltaTheta = mod(thetaVec - meanTheta + pi, 2*pi) - pi;

        % Histogram → PDF
        counts = histcounts(deltaTheta, edges);
        totalSamples = numel(deltaTheta);
        pdfVals = counts ./ (totalSamples * binWidth);
        pdfSum = pdfSum + pdfVals;
    end

    % Average the PDF over the two files
    pdfAvg = pdfSum / 2;

    % Plot averaged curve
    hPlot(k) = plot(binCenters, pdfAvg, ...
        '-', ...
        'Marker', markerList{k}, ...        % <-- Different marker for each curve
        'LineWidth', 3, ...
        'MarkerSize', 10, ...
        'Color', colorOrder(k,:), ...
        'MarkerFaceColor', colorOrder(k,:), ...
        'MarkerEdgeColor', colorOrder(k,:));
end

% Axis formatting
xlabel('\delta\theta (radians)', 'FontName', 'Times New Roman', 'FontSize', 40);
ylabel('P(\delta\theta)', 'FontName', 'Times New Roman', 'FontSize', 40);
xlim([-5*pi/8, 5*pi/8]);
xticks([-pi/2, -pi/4, 0, pi/4, pi/2]);
xticklabels({'-π/2','-π/4','0','π/4','π/2'});
set(ax, 'FontName','Times New Roman', 'FontSize', 40, ...
        'LineWidth', 5, 'TickDir','out', 'Box','on');

legend(hPlot, {'10% MF','30% MF','50% MF','70% MF'}, ...
       'Location','northeast', ...
       'FontName','Times New Roman', ...
       'FontSize', 32, ...
       'Box','off');

exportgraphics(gcf, fullfile('Results','Pdistribution.tif'), 'Resolution', 300);